// <auto-generated />
using EcoAlert.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace EcoAlert.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoAlert.Domain.Entities.LimiarEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LIMIAR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MsgMax")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MSG_MAX");

                    b.Property<string>("MsgMin")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MSG_MIN");

                    b.Property<string>("ParametroSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PARAMETRO_SENSOR");

                    b.Property<string>("RecomendacaoAlerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RECOMENDACAO_ALERTA");

                    b.Property<double>("ValorMax")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALOR_MAX");

                    b.Property<double>("ValorMin")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALOR_MIN");

                    b.HasKey("Id");

                    b.ToTable("TB_LIMIAR_CLIMATICO");
                });
#pragma warning restore 612, 618
        }
    }
}
